# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - denso_joint_trajectory_controller

  denso_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - c_210_cobotta_pro_joint_1
      - c_210_cobotta_pro_joint_2
      - c_210_cobotta_pro_joint_3
      - c_210_cobotta_pro_joint_4
      - c_210_cobotta_pro_joint_5
      - c_210_cobotta_pro_joint_6
    action_ns: follow_joint_trajectory
    default: true