# Default initial positions for cobotta_cell's ros2_control fake system

initial_positions:
  c_210_cobotta_pro_joint_1: 0.026
  c_210_cobotta_pro_joint_2: 0.188
  c_210_cobotta_pro_joint_3: 1.374
  c_210_cobotta_pro_joint_4: -3.1502
  c_210_cobotta_pro_joint_5: -1.4897
  c_210_cobotta_pro_joint_6: 0.0347
  c_212_pneumatic_disassembly_unit_with_2_cylinders_pull_cylinder_joint: 0.01
  c_212_pneumatic_disassembly_unit_with_2_cylinders_push_cylinder_joint: 0.01
  c_213_schunk_egp64_gripper_finger_1_joint: 0.03
  c_213_schunk_egp64_gripper_finger_2_joint: 0.03
