# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - denso_joint_trajectory_controller
    - vtem_point_controller
    - schunk_egp64_gripper_controller

  denso_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - c_210_cobotta_pro_joint_1
      - c_210_cobotta_pro_joint_2
      - c_210_cobotta_pro_joint_3
      - c_210_cobotta_pro_joint_4
      - c_210_cobotta_pro_joint_5
      - c_210_cobotta_pro_joint_6
  vtem_point_controller:
    type: GripperCommand
    joints:
      - c_212_pneumatic_disassembly_unit_with_2_cylinders_pull_cylinder_joint
      - c_212_pneumatic_disassembly_unit_with_2_cylinders_push_cylinder_joint
    action_ns: gripper_cmd
    default: true
  schunk_egp64_gripper_controller:
    type: GripperCommand
    joints:
      - c_213_schunk_egp64_gripper_finger_1_joint
      - c_213_schunk_egp64_gripper_finger_2_joint
    action_ns: gripper_cmd
    default: true
