initial_positions:
  c_210_cobotta_pro_joint_1: 0.026
  c_210_cobotta_pro_joint_2: 0.188
  c_210_cobotta_pro_joint_3: 1.374
  c_210_cobotta_pro_joint_4: -3.1502
  c_210_cobotta_pro_joint_5: -1.4897
  c_210_cobotta_pro_joint_6: 0.0347

c_210_cobotta_pro_joint_1: 0.026
c_210_cobotta_pro_joint_2: 0.188
c_210_cobotta_pro_joint_3: 1.374
c_210_cobotta_pro_joint_4: -3.1502
c_210_cobotta_pro_joint_5: -1.4897
c_210_cobotta_pro_joint_6: 0.0347
